//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class CurvePointLabel
	{
		private float left;
		private float width;
		private string text;
		public CurvePointLabel (float left, float width, string text)
		{ 
			this.left = left;
			this.text = text;
			this.width = width;
		}
		public string getText() { return this.text; }
		public float getLeft() { return this.left; }
		public float getWidth() { return this.width; }
	}
}

