//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp
{
		public interface DrawClockFunctions
		{
		void drawClock(Rect inPosition, float inHours, float inMinutes, float inSeconds, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize);
		void positionClock(float left, float top, float size, float hours, float minutes, float inSeconds, string text, GUIStyle myStyle, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize);
		void positionClock(float left, float top, float size, string text, GUIStyle myStyle, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize);
		}
}

