//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
namespace AssemblyCSharp
{
		public class DrawClockFunctionsImpl : DrawClockFunctions
		{
				private ClockFunctions myClockFunctions;
				private TimeSpan timespan;
				
				public DrawClockFunctionsImpl ()
				{
					myClockFunctions = new ClockFunctionsImpl ();
				}

				public void positionClock(float left, float top, float size, float hours, float minutes, float seconds, string text, GUIStyle myStyle, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize) {
					Rect position = new Rect(left , top, size, size);
					drawClock (position, hours, minutes, seconds, analogGuiClock, analogClockBackground, analogClockCenter, analogClockCenterSize);
					string myLabel = myClockFunctions.timeLabel (text, hours, minutes);
					if (!text.Equals(""))	GUI.Label(new Rect(left, top-25, size, 20), myLabel, myStyle);
				}
				public void positionClock(float left, float top, float size, string text, GUIStyle myStyle, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize) {
					// no time sent in so generate current hours minutes and seconds
					
					timespan = DateTime.Now.TimeOfDay;
					float hours = (float)timespan.Hours;
					float minutes = (float)timespan.Minutes;
					float seconds = (float)timespan.TotalSeconds;

					Rect position = new Rect(left , top, size, size);
					drawClock (position, hours, minutes, seconds, analogGuiClock, analogClockBackground, analogClockCenter, analogClockCenterSize);
					string myLabel = myClockFunctions.timeLabel (text, hours, minutes);
					if (!text.Equals(""))	GUI.Label(new Rect(left, top-25, size, 20), myLabel, myStyle);
				}
				public void drawClock(Rect inPosition, float inHours, float inMinutes, float inSeconds, OnGUIClockHands analogGuiClock, Texture analogClockBackground, Texture analogClockCenter, float analogClockCenterSize) {
					if (analogGuiClock != null)
					{
						//position the clock face
						if (analogClockBackground != null)
						{
							GUI.DrawTexture(inPosition, analogClockBackground);
						}
				
						// position the clock hands
						analogGuiClock.Draw(inPosition, inHours, inMinutes, inSeconds);
				
						// position the clock centre
						if (analogClockCenter != null)
						{
							GUI.DrawTexture(new Rect(inPosition.center.x - analogClockCenterSize * 0.5f, inPosition.center.y - analogClockCenterSize * 0.5f, analogClockCenterSize, analogClockCenterSize), analogClockBackground);
						}
					}
				}
		}
}

