//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public interface Player
	{
		int getId();
		int getcurrentPlayerLevel();
		PlayerLevelFlags getPlayerLevelFlags() ;
		Level getcurrentQuestionLevel();
		String getName();
		void updateScore(int quizId, int score);
		bool updatePlayerLevel();
		void updatePlayerLevel (int currentPlayerLevel, int currentQuestionLevel);
		int getScore(int quizId);
		//string getplayerLevelsHash(); // remove, just a test function
	}
}

