//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	[Serializable]
	public class PlayerLevelFlags
	{
		public readonly int id;
		public readonly bool textTips;
		public readonly bool arcTools;
		public readonly bool sliderTool;
		public PlayerLevelFlags (int id, bool textTips, bool arcTools, bool sliderTool)
		{
			this.id = id;
			this.textTips = textTips;
			this.arcTools = arcTools;
			this.sliderTool = sliderTool;
		}
	}
}

